### ISSUE TITLE
All sensors unavailable

### ISSUE THREAD

**Issue by ricobach** [JBoye/HA-Aula#11]
After the last update  all aula sensor are unavailable and i get the errors in the log..   i have verified that the unilogin are working, so i do not that is the issue.. 

```
2022-08-29 10:07:15.610 ERROR (MainThread) [custom_components.aula.sensor] Unexpected error fetching sensor data: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 205, in _async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 164, in _async_update_data
    return await self.update_method()
  File "/config/custom_components/aula/sensor.py", line 17, in async_update_data
    await hass.async_add_executor_job(client.update_data)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/aula/client.py", line 58, in update_data
    self.login()
  File "/config/custom_components/aula/client.py", line 45, in login
    self._profiles = self._session.get(API + "?method=profiles.getProfilesByLogin").json()["data"]["profiles"]
TypeError: 'NoneType' object is not subscriptable
2022-08-29 10:07:16.541 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up aula platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 281, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/aula/sensor.py", line 34, in async_setup_platform
    for i, child in enumerate(client._children):
AttributeError: 'Client' object has no attribute '_children'
```

**Comment by Bredahl88** [comment]
I belive that the url have change. Also i belive that the username and password was on same url now is split up, maybe?

**Comment by jannsvej** [comment]
The API changed version to 14. You can fix it manually by changing v13 to v14 in const.py.

**Comment by ricobach** [comment]
Changing the API version did the trick.  Thanks
