### ISSUE TITLE
Fejl

### ISSUE THREAD

**Issue by ulfendk** [JBoye/HA-Aula#2]
Hej, det var lige det jeg søgte efter! Tak.  Desværre kan jeg ikke få det til at virke og får følgende fejl i HA log:

```
2021-12-01 08:24:03 ERROR (MainThread) [custom_components.aula.sensor] Unexpected error fetching sensor data: 'NoneType' object is not subscriptable
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 187, in _async_refresh
self.data = await self._async_update_data()
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 147, in _async_update_data
return await self.update_method()
File "/config/custom_components/aula/sensor.py", line 17, in async_update_data
await hass.async_add_executor_job(client.update_data)
File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
result = self.fn(*self.args, **self.kwargs)
File "/config/custom_components/aula/client.py", line 57, in update_data
self.login()
File "/config/custom_components/aula/client.py", line 44, in login
self._profiles = self._session.get("https://www.aula.dk/api/v11/?method=profiles.getProfilesByLogin").json()["data"]["profiles"]
TypeError: 'NoneType' object is not subscriptable
2021-12-01 08:24:03 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up aula platform for sensor
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
await asyncio.shield(task)
File "/config/custom_components/aula/sensor.py", line 34, in async_setup_platform
for i, child in enumerate(client._children):
AttributeError: 'Client' object has no attribute '_children'
```

Har du nogen idé om hvad der måtte være galt?

Venlig hilsen

**Comment by JBoye** [comment]
@ulfendk Jeg vil gætte på at du måske bruger barnets login i stedet for forældrens?

**Comment by ulfendk** [comment]
Desværre ikke det.  Jeg bruger mit eget login.

**Comment by JBoye** [comment]
Ahh - Jeg kan se at Aula lige har skiftet fra api v11 til API v12. Det skal jeg have kigget nærmere på

Som et quickfix, så kan du forsøge at erstatte `https://www.aula.dk/api/v11` til `https://www.aula.dk/api/v12`

**Comment by ulfendk** [comment]
Tak, jeg prøver i aften.

**Comment by JBoye** [comment]
Jeg har lagt en ny version op, du kan bare opdatere via HACS

**Comment by ulfendk** [comment]
Den er nu afprøvet og der er ikke fejl i loggen.

Desværre tror jeg det er UniLogin der ikke virker.  Jeg kan heller ikke logge på aula.dk med UniLogin - i stedet sendes jeg videre til kommunens system, som jeg ikke kan logge på, til trods for at jeg har login og adgangskode.

Tak for forsøget.

**Comment by JBoye** [comment]
👍
